### ISSUE TITLE
Multi-colour setup: some comments

### ISSUE THREAD

**Issue by iandobbie** [DiamondLightSource/PySIMRecon#63]
I have some four channel data with associated otfs that I have setup for reconstruction and have a few comments on the process.

What I needed was specific otf, line spacing and k0 values, probably a common use case for this type of setup. in a single camera system the k0 values may not be needed but the OMX this data came from has variable angles per channel due to the mechanism is uses to change line spacing. 

So I add channel specific configs and the relevant otfs to the config.ini. An example channel config file is:

```  
[otf config]

[recon config]
#channel specific params
#line spacing
ls=0.191
#k0 values
k0angles=-0.708800,-1.747400,-2.949500
```

I found I had to add the [otf config] section to this file or it generated an error, yet this section is empty as we are using the main defaults. Why do we need this section?

I managed to typo one of the otf file names. This generated an error and a python call trace output, but also continued to produce reconstruction and the 3 channels with valid otfs worked but the final result was an empty file as one channel was missing. I think a missing otf file should produce a clear error and stop the processing as you are unlikely to want an image missing channels and the final steps are producing an empty image file, maybe making people think it has work when it doesn't.

**Comment by thomasmfish** [comment]
Okay, I've been working on the assumption that it's worth processing everything it can. I've made a couple of PRs to address the other points though. The tricky part is that, because the cudasirecon process crashes out if it fails, it might have to handle missing channels sometimes. That said, I could add an argument along the lines of `--allow-missing-channels` that decides if it will go ahead despite missing configuration of some channels. What do you think?
